# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy code
COPY . .

# Build TypeScript
RUN npm run build:ts

# Stage 2: Production
FROM node:20-alpine AS production
WORKDIR /app

# Copy built code & node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

# Expose API port
EXPOSE 3000

# Default command: API
CMD ["node", "dist/app.js"]